include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - pigeons/**
    - '**/*.g.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    use_setters_to_change_properties: false
