// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.pdp_todo_app.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlatformApisPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ApiMessageType(val raw: Int) {
  PING(0),
  PONG(1);

  companion object {
    fun ofRaw(raw: Int): ApiMessageType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ApiConnectivityStatus(val raw: Int) {
  WIFI(0),
  MOBILE(1),
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): ApiConnectivityStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApiChannelMessage (
  val type: ApiMessageType,
  val id: String,
  val payload: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApiChannelMessage {
      val type = pigeonVar_list[0] as ApiMessageType
      val id = pigeonVar_list[1] as String
      val payload = pigeonVar_list[2] as String
      return ApiChannelMessage(type, id, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      id,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ApiChannelMessage
    return PlatformApisPigeonUtils.deepEquals(this.type, other.type) && PlatformApisPigeonUtils.deepEquals(this.id, other.id) && PlatformApisPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApisPigeonUtils.deepHash(this.type)
    result = 31 * result + PlatformApisPigeonUtils.deepHash(this.id)
    result = 31 * result + PlatformApisPigeonUtils.deepHash(this.payload)
    return result
  }
  override fun toString(): String {
    return "ApiChannelMessage(type=$type, id=$id, payload=$payload)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApiMapClick (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApiMapClick {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return ApiMapClick(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ApiMapClick
    return PlatformApisPigeonUtils.deepEquals(this.latitude, other.latitude) && PlatformApisPigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApisPigeonUtils.deepHash(this.latitude)
    result = 31 * result + PlatformApisPigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "ApiMapClick(latitude=$latitude, longitude=$longitude)"
  }
}
private open class PlatformApisPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ApiMessageType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ApiConnectivityStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApiChannelMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApiMapClick.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ApiMessageType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ApiConnectivityStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ApiChannelMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ApiMapClick -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val PlatformApisPigeonMethodCodec = StandardMethodCodec(PlatformApisPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BatteryHostApi {
  fun getBatteryLevel(): Long

  companion object {
    /** The codec used by BatteryHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApisPigeonCodec()
    }
    /** Sets up an instance of `BatteryHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BatteryHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdp_todo_app.BatteryHostApi.getBatteryLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBatteryLevel())
            } catch (exception: Throwable) {
              PlatformApisPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MessagesHostApi {
  fun sendPing(ping: ApiChannelMessage): ApiChannelMessage

  companion object {
    /** The codec used by MessagesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApisPigeonCodec()
    }
    /** Sets up an instance of `MessagesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MessagesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdp_todo_app.MessagesHostApi.sendPing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pingArg = args[0] as ApiChannelMessage
            val wrapped: List<Any?> = try {
              listOf(api.sendPing(pingArg))
            } catch (exception: Throwable) {
              PlatformApisPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PlatformApisPigeonStreamHandler<T>(
    val wrapper: PlatformApisPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PlatformApisPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class ConnectivityEventsStreamHandler : PlatformApisPigeonEventChannelWrapper<ApiConnectivityStatus> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ConnectivityEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.pdp_todo_app.PlatformEventApi.connectivityEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PlatformApisPigeonStreamHandler<ApiConnectivityStatus>(streamHandler)
      EventChannel(messenger, channelName, PlatformApisPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PlatformApisPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ApiConnectivityStatus>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnMapClickStreamHandler : PlatformApisPigeonEventChannelWrapper<ApiMapClick> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnMapClickStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.pdp_todo_app.PlatformEventApi.onMapClick"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PlatformApisPigeonStreamHandler<ApiMapClick>(streamHandler)
      EventChannel(messenger, channelName, PlatformApisPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PlatformApisPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ApiMapClick>) {}

override fun onCancel(p0: Any?) {}
}
      
