// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PlatformApisPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum ApiMessageType: Int, CaseIterable {
  case ping = 0
  case pong = 1
}

enum ApiConnectivityStatus: Int, CaseIterable {
  case wifi = 0
  case mobile = 1
  case none = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct ApiChannelMessage: Hashable, CustomStringConvertible {
  var type: ApiMessageType
  var id: String
  var payload: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ApiChannelMessage? {
    let type = pigeonVar_list[0] as! ApiMessageType
    let id = pigeonVar_list[1] as! String
    let payload = pigeonVar_list[2] as! String

    return ApiChannelMessage(
      type: type,
      id: id,
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      id,
      payload,
    ]
  }
  static func == (lhs: ApiChannelMessage, rhs: ApiChannelMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PlatformApisPigeonInternal.deepEquals(lhs.type, rhs.type) && PlatformApisPigeonInternal.deepEquals(lhs.id, rhs.id) && PlatformApisPigeonInternal.deepEquals(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ApiChannelMessage")
    PlatformApisPigeonInternal.deepHash(value: type, hasher: &hasher)
    PlatformApisPigeonInternal.deepHash(value: id, hasher: &hasher)
    PlatformApisPigeonInternal.deepHash(value: payload, hasher: &hasher)
  }

  public var description: String {
    return "ApiChannelMessage(type: \(String(describing: type)), id: \(String(describing: id)), payload: \(String(describing: payload)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ApiMapClick: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ApiMapClick? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return ApiMapClick(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: ApiMapClick, rhs: ApiMapClick) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PlatformApisPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && PlatformApisPigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ApiMapClick")
    PlatformApisPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    PlatformApisPigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "ApiMapClick(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

private class PlatformApisPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ApiMessageType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ApiConnectivityStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return ApiChannelMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return ApiMapClick.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PlatformApisPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ApiMessageType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ApiConnectivityStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ApiChannelMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ApiMapClick {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PlatformApisPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PlatformApisPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PlatformApisPigeonCodecWriter(data: data)
  }
}

class PlatformApisPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PlatformApisPigeonCodec(readerWriter: PlatformApisPigeonCodecReaderWriter())
}

var platformApisPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: PlatformApisPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BatteryHostApi {
  func getBatteryLevel() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BatteryHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApisPigeonCodec.shared }
  /// Sets up an instance of `BatteryHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BatteryHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getBatteryLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdp_todo_app.BatteryHostApi.getBatteryLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBatteryLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBatteryLevelChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MessagesHostApi {
  func sendPing(ping: ApiChannelMessage) throws -> ApiChannelMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MessagesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApisPigeonCodec.shared }
  /// Sets up an instance of `MessagesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MessagesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let sendPingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdp_todo_app.MessagesHostApi.sendPing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendPingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pingArg = args[0] as! ApiChannelMessage
        do {
          let result = try api.sendPing(ping: pingArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendPingChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class ConnectivityEventsStreamHandler: PigeonEventChannelWrapper<ApiConnectivityStatus> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: ConnectivityEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.pdp_todo_app.PlatformEventApi.connectivityEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<ApiConnectivityStatus>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: platformApisPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class OnMapClickStreamHandler: PigeonEventChannelWrapper<ApiMapClick> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: OnMapClickStreamHandler) {
    var channelName = "dev.flutter.pigeon.pdp_todo_app.PlatformEventApi.onMapClick"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<ApiMapClick>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: platformApisPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
